databases:
  - name: less_is_more
    databaseName: less_is_more_production
    user: less_is_more

services:
  - type: web
    name: less_is_more
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: less_is_more
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
