class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  COUNTRIES = [
#     "Africa Eastern and Southern",
# "Afghanistan",
# "Africa Western and Central",
# "Angola",
"Albania",
"Andorra",
# "Arab World",
# "United Arab Emirates",
# "Argentina",
# "Armenia",
# "Antigua and Barbuda",
"Australia",
"Austria",
"Azerbaijan",
"Burundi",
"Belgium",
"Benin",
"Burkina Faso",
"Bangladesh",
"Bulgaria",
"Bahrain",
"Bahamas The",
"Bosnia and Herzegovina",
"Belarus",
"Belize",
"Bolivia",
"Brazil",
"Barbados",
"Brunei Darussalam",
"Bhutan",
"Botswana",
"Central African Republic",
"Canada",
"Central Europe and the Baltics",
"Switzerland",
"Chile",
"China",
"Cote d'Ivoire",
"Cameroon",
"Congo Rep.",
"Colombia",
"Comoros",
"Cabo Verde",
"Costa Rica",
"Cuba",
"Cyprus",
"Czech Republic",
"Germany",
"Djibouti",
"Dominica",
"Denmark",
"Dominican Republic",
"Algeria",
"Ecuador",
"Egypt Arab Rep.",
"Euro area",
"Eritrea",
"Spain",
"Estonia",
"Ethiopia",
"Finland",
"Fiji",
"France",
"Gabon",
"United Kingdom",
"Georgia",
"Ghana",
"Guinea",
"Gambia The",
"Guinea-Bissau",
"Equatorial Guinea",
"Greece",
"Grenada",
"Guatemala",
"Guyana",
"High income",
"Honduras",
"Croatia",
"Haiti",
"Hungary",
"IBRD only",
"IDA & IBRD total",
"IDA total",
"IDA blend",
"Indonesia",
"IDA only",
"India",
"Ireland",
"Iran Islamic Rep.",
"Iraq",
"Iceland",
"Israel",
"Italy",
"Jamaica",
"Jordan",
"Japan",
"Kazakhstan",
"Kenya",
"Kyrgyz Republic",
"Cambodia",
"Kiribati",
"St. Kitts and Nevis",
"Korea Rep.",
"Kuwait",
"Latin America & Caribbean (excluding high income)",
"Lao PDR",
"Lebanon",
"Liberia",
"Libya",
"St. Lucia",
"Latin America & Caribbean",
"Least developed countries: UN classification",
"Low income",
"Liechtenstein",
"Sri Lanka",
"Lower middle income",
"Low & middle income",
"Lesotho",
"Late-demographic dividend",
"Lithuania",
"Luxembourg",
"Latvia",
"Morocco",
"Moldova",
"Madagascar",
"Maldives",
"Middle East & North Africa",
"Mexico",
"Marshall Islands",
"Middle income",
"North Macedonia",
"Mali",
"Malta",
"Myanmar",
"Middle East & North Africa (excluding high income)",
"Montenegro",
"Mongolia",
"Mozambique",
"Mauritania",
"Mauritius",
"Malawi",
"Malaysia",
"North America",
"Namibia",
"Niger",
"Nigeria",
"Nicaragua",
"Netherlands",
"Norway",
"Nepal",
"Nauru",
"New Zealand",
"OECD members",
"Oman",
"Other small states",
"Pakistan",
"Panama",
"Peru",
"Philippines",
"Palau",
"Papua New Guinea",
"Poland",
"Pre-demographic dividend",
"Korea Dem. People's Rep.",
"Portugal",
"Paraguay",
"Pacific island small states",
"Post-demographic dividend",
"Qatar",
"Romania",
"Russian Federation",
"Rwanda",
"South Asia",
"Saudi Arabia",
"Sudan",
"Senegal",
"Singapore",
"Solomon Islands",
"Sierra Leone",
"El Salvador",
"Somalia",
"Serbia",
"Sub-Saharan Africa (excluding high income)",
"South Sudan",
"Sub-Saharan Africa",
"Small states",
"Sao Tome and Principe",
"Suriname",
"Slovak Republic",
"Slovenia",
"Sweden",
"Eswatini",
"Seychelles",
"Syrian Arab Republic",
"Chad",
"East Asia & Pacific (IDA & IBRD countries)",
"Europe & Central Asia (IDA & IBRD countries)",
"Togo",
"Thailand",
"Tajikistan",
"Turkmenistan",
"Latin America & the Caribbean (IDA & IBRD countries)",
"Timor-Leste",
"Middle East & North Africa (IDA & IBRD countries)",
"Tonga",
"South Asia (IDA & IBRD)",
"Sub-Saharan Africa (IDA & IBRD countries)",
"Trinidad and Tobago",
"Tunisia",
"Turkiye",
"Tuvalu",
"Tanzania",
"Uganda",
"Ukraine",
"Upper middle income",
"Uruguay",
"United States",
"Uzbekistan",
"St. Vincent and the Grenadines",
"Venezuela RB",
"Vietnam",
"Vanuatu",
"World",
"Samoa",
"Yemen Rep.",
"South Africa",
"Zambia",
"Zimbabwe",]
end
